### PR TITLE
Remove unused std::io::Write import

### LINKED ISSUE #27: Unused import std::io::Write
I ran `cargo install cargo-count` on nightly. It worked but I saw this warning:

```
   Compiling cargo-count v0.2.1
.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-count-0.2.1/src/main.rs:190:5: 190:19 warning: unused import, #[warn(unused_imports)] on by default
.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-count-0.2.1/src/main.rs:190 use std::io::Write;
                                                                                      ^~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Closes #27

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
ping

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by kbknapp** [comment]
Thanks!

**Comment by kbknapp** [comment]
@homu r+

**Pull request merged**
